//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reserva_Restaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comidas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comidas()
        {
            this.IngredientesComida = new HashSet<IngredientesComida>();
            this.MenuRestaurantes = new HashSet<MenuRestaurantes>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string DescricaoCurta { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> IdCategoria { get; set; }
    
        public virtual CategoriasComida CategoriasComida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientesComida> IngredientesComida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuRestaurantes> MenuRestaurantes { get; set; }
    }
}
