//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reserva_Restaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enderecos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enderecos()
        {
            this.Pessoas = new HashSet<Pessoas>();
            this.Restaurantes = new HashSet<Restaurantes>();
        }
    
        public int ID { get; set; }
        public string Cep { get; set; }
        public Nullable<int> IdCidade { get; set; }
    
        public virtual Cidades Cidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pessoas> Pessoas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restaurantes> Restaurantes { get; set; }
    }
}
