//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reserva_Restaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientesComida
    {
        public int ID { get; set; }
        public Nullable<int> IdIngrediente { get; set; }
        public Nullable<int> IdComida { get; set; }
        public Nullable<double> Quantidade { get; set; }
    
        public virtual Comidas Comidas { get; set; }
        public virtual Ingredientes Ingredientes { get; set; }
    }
}
