//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reserva_Restaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MesasRestaurante
    {
        public int ID { get; set; }
        public Nullable<int> IdRestaurante { get; set; }
        public string CodigoMesa { get; set; }
        public Nullable<int> QuantidadeCadeiras { get; set; }
        public Nullable<bool> LivreReserva { get; set; }
    
        public virtual Restaurantes Restaurantes { get; set; }
    }
}
