//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reserva_Restaurante.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbReservaRestauranteEntities : DbContext
    {
        public dbReservaRestauranteEntities()
            : base("name=dbReservaRestauranteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avaliacoes> Avaliacoes { get; set; }
        public virtual DbSet<CategoriasComida> CategoriasComida { get; set; }
        public virtual DbSet<Cidades> Cidades { get; set; }
        public virtual DbSet<Comidas> Comidas { get; set; }
        public virtual DbSet<Enderecos> Enderecos { get; set; }
        public virtual DbSet<Ingredientes> Ingredientes { get; set; }
        public virtual DbSet<IngredientesComida> IngredientesComida { get; set; }
        public virtual DbSet<MenuRestaurantes> MenuRestaurantes { get; set; }
        public virtual DbSet<MesasRestaurante> MesasRestaurante { get; set; }
        public virtual DbSet<Pessoas> Pessoas { get; set; }
        public virtual DbSet<PreferenciasPessoa> PreferenciasPessoa { get; set; }
        public virtual DbSet<Reservas> Reservas { get; set; }
        public virtual DbSet<Restaurantes> Restaurantes { get; set; }
    }
}
