//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reserva_Restaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreferenciasPessoa
    {
        public int ID { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public Nullable<int> IdPessoa { get; set; }
        public Nullable<bool> Gosta { get; set; }
    
        public virtual CategoriasComida CategoriasComida { get; set; }
        public virtual Pessoas Pessoas { get; set; }
    }
}
