//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reserva_Restaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservas()
        {
            this.Avaliacoes = new HashSet<Avaliacoes>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> QuantidadePessoas { get; set; }
        public Nullable<int> IdPessoa { get; set; }
        public Nullable<int> IdRestaurante { get; set; }
        public Nullable<System.DateTime> DataCancelamento { get; set; }
        public byte[] Rubrica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Avaliacoes> Avaliacoes { get; set; }
        public virtual Pessoas Pessoas { get; set; }
        public virtual Restaurantes Restaurantes { get; set; }
    }
}
