//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reserva_Restaurante.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurantes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurantes()
        {
            this.MenuRestaurantes = new HashSet<MenuRestaurantes>();
            this.MesasRestaurante = new HashSet<MesasRestaurante>();
            this.Reservas = new HashSet<Reservas>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> IdEndereco { get; set; }
        public string Nome { get; set; }
        public Nullable<System.TimeSpan> HoraAbertura { get; set; }
        public Nullable<System.TimeSpan> HoraFechamento { get; set; }
    
        public virtual CategoriasComida CategoriasComida { get; set; }
        public virtual Enderecos Enderecos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuRestaurantes> MenuRestaurantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MesasRestaurante> MesasRestaurante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
